const upComingMovies = {
  results: [
    {
      adult: false,
      backdrop_path: "/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
      genre_ids: [28, 80, 53],
      id: 1249289,
      original_language: "en",
      original_title: "Alarum",
      overview:
        "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
      popularity: 1403.09,
      poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
      release_date: "2025-01-16",
      title: "Alarum",
      video: false,
      vote_average: 5.814,
      vote_count: 137,
    },
    {
      adult: false,
      backdrop_path: "/u7AZ5CdT2af8buRjmYCPXNyJssd.jpg",
      genre_ids: [28, 35],
      id: 1160956,
      original_language: "zh",
      original_title: "熊猫计划",
      overview:
        "International action star Jackie Chan is invited to the adoption ceremony of a rare baby panda, but after an international crime syndicate attempts to kidnap the bear, Jackie has to save the bear using his stunt work skills.",
      popularity: 1202.264,
      poster_path: "/xVS9XiO9upp2SnWx6KpBYb79hLR.jpg",
      release_date: "2024-10-01",
      title: "Panda Plan",
      video: false,
      vote_average: 5.818,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: "/nNF4ZB0UDL4qAUjQfbYZDq3Ck7J.jpg",
      genre_ids: [27, 53],
      id: 710295,
      original_language: "en",
      original_title: "Wolf Man",
      overview:
        "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
      popularity: 1086.996,
      poster_path: "/jTPBMPTgk9zOUGSkWcoOGbX8cTi.jpg",
      release_date: "2025-01-15",
      title: "Wolf Man",
      video: false,
      vote_average: 6.406,
      vote_count: 249,
    },
    {
      adult: false,
      backdrop_path: "/h7r6LZ32dgLwtwSW3CxoWIYD9pr.jpg",
      genre_ids: [27, 14],
      id: 426063,
      original_language: "en",
      original_title: "Nosferatu",
      overview:
        "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      popularity: 1030.383,
      poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      release_date: "2024-12-25",
      title: "Nosferatu",
      video: false,
      vote_average: 6.65,
      vote_count: 1965,
    },
    {
      adult: false,
      backdrop_path: "/kEYWal656zP5Q2Tohm91aw6orlT.jpg",
      genre_ids: [18, 35, 10749],
      id: 1064213,
      original_language: "en",
      original_title: "Anora",
      overview:
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
      popularity: 530.515,
      poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      release_date: "2024-10-14",
      title: "Anora",
      video: false,
      vote_average: 7.1,
      vote_count: 968,
    },
    {
      adult: false,
      backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      genre_ids: [16, 14, 12],
      id: 823219,
      original_language: "lv",
      original_title: "Straume",
      overview:
        "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      popularity: 472.672,
      poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      release_date: "2024-08-29",
      title: "Flow",
      video: false,
      vote_average: 8.343,
      vote_count: 1076,
    },
    {
      adult: false,
      backdrop_path: "/i3CAo9UMGsvlU9k3Svd63rRDeZx.jpg",
      genre_ids: [16, 18, 35],
      id: 1064486,
      original_language: "en",
      original_title: "Memoir of a Snail",
      overview:
        "Forcibly separated from her twin brother when they are orphaned, a melancholic misfit learns how to find confidence within herself amid the clutter of misfortunes and everyday life.",
      popularity: 453.963,
      poster_path: "/lWh5OlerPR1c1cfn1ZLq0lpqFds.jpg",
      release_date: "2024-10-17",
      title: "Memoir of a Snail",
      video: false,
      vote_average: 7.673,
      vote_count: 136,
    },
    {
      adult: false,
      backdrop_path: "/7bIWKyWdT04HTY3PqLETT8CH7jo.jpg",
      genre_ids: [28, 80, 53],
      id: 974453,
      original_language: "en",
      original_title: "Absolution",
      overview:
        "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
      popularity: 443.01,
      poster_path: "/gt70JOD9xsPlpJnuBJAWdOT4yRg.jpg",
      release_date: "2024-10-31",
      title: "Absolution",
      video: false,
      vote_average: 5.838,
      vote_count: 296,
    },
    {
      adult: false,
      backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
      genre_ids: [27, 53],
      id: 1138194,
      original_language: "en",
      original_title: "Heretic",
      overview:
        "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
      popularity: 371.198,
      poster_path: "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
      release_date: "2024-10-31",
      title: "Heretic",
      video: false,
      vote_average: 7.2,
      vote_count: 1055,
    },
    {
      adult: false,
      backdrop_path: "/mKIxSo3p1QKlsdegcOwapcbiV74.jpg",
      genre_ids: [28, 80, 53],
      id: 604685,
      original_language: "en",
      original_title: "Den of Thieves 2: Pantera",
      overview:
        "Big Nick is back on the hunt in Europe and closing in on Donnie, who is embroiled in the treacherous and unpredictable world of diamond thieves and the infamous Panther mafia, as they plot a massive heist of the world's largest diamond exchange.",
      popularity: 367.762,
      poster_path: "/zLHq7fQA3xpck5UIHcRYgip5pQD.jpg",
      release_date: "2025-01-08",
      title: "Den of Thieves 2: Pantera",
      video: false,
      vote_average: 6.7,
      vote_count: 198,
    },
    {
      adult: false,
      backdrop_path: "/sc1abgWNXc29wSBaerrjGBih06l.jpg",
      genre_ids: [878, 27, 35, 53],
      id: 1084199,
      original_language: "en",
      original_title: "Companion",
      overview:
        "During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.",
      popularity: 354.808,
      poster_path: "/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
      release_date: "2025-01-22",
      title: "Companion",
      video: false,
      vote_average: 7.1,
      vote_count: 197,
    },
    {
      adult: false,
      backdrop_path: "/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 311.62,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.451,
      vote_count: 36418,
    },
    {
      adult: false,
      backdrop_path: "/9s9o9RT9Yj6nDuRJjnJm78WFoFl.jpg",
      genre_ids: [28, 27, 53, 878],
      id: 1051896,
      original_language: "en",
      original_title: "Arcadian",
      overview:
        "In the near future, on a decimated Earth, Paul and his twin sons face terror at night when ferocious creatures awaken. When Paul is nearly killed, the boys come up with a plan for survival, using everything their father taught them to keep him alive.",
      popularity: 285.25,
      poster_path: "/h4T8Xeydkw53h9uIbulYsss25UF.jpg",
      release_date: "2024-04-12",
      title: "Arcadian",
      video: false,
      vote_average: 6.1,
      vote_count: 592,
    },
    {
      adult: false,
      backdrop_path: "/u2eA9pqi1q3DvevT7RuDuJHxxBT.jpg",
      genre_ids: [18, 53],
      id: 974950,
      original_language: "fr",
      original_title: "Emilia Pérez",
      overview:
        "Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization.",
      popularity: 284.311,
      poster_path: "/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg",
      release_date: "2024-08-21",
      title: "Emilia Pérez",
      video: false,
      vote_average: 7.123,
      vote_count: 1172,
    },
    {
      adult: false,
      backdrop_path: "/8eifdha9GQeZAkexgtD45546XKx.jpg",
      genre_ids: [878, 28, 53],
      id: 822119,
      original_language: "en",
      original_title: "Captain America: Brave New World",
      overview:
        "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
      popularity: 278.408,
      poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
      release_date: "2025-02-12",
      title: "Captain America: Brave New World",
      video: false,
      vote_average: 8.4,
      vote_count: 5,
    },
    {
      adult: false,
      backdrop_path: "/p23kiJvHLTEzVFYayGa3WqEluc1.jpg",
      genre_ids: [35, 9648, 28],
      id: 1357305,
      original_language: "zh",
      original_title: "唐探1900",
      overview:
        "In 1900s San Francisco, a white woman is murdered in Chinatown and the suspect is a Chinese man. The murder causes a social shock and the public calls for Chinatown to be outlawed. Chinese medicine practitioner Qin Fu and Chinese man Ghost are involved in the case, and they race against time to find the murderer amidst a battle of wits and courage.",
      popularity: 251.668,
      poster_path: "/3UfCRovdz0hoRsOTGyKIyvv5wu7.jpg",
      release_date: "2025-01-29",
      title: "Detective Chinatown 1900",
      video: false,
      vote_average: 6,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: "/66nlC5LDZmDUWONGkUZT2BrOszG.jpg",
      genre_ids: [18, 9648, 53],
      id: 974576,
      original_language: "en",
      original_title: "Conclave",
      overview:
        "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
      popularity: 246.342,
      poster_path: "/vYEyxF1UT779RiEalpMjUT6kfdf.jpg",
      release_date: "2024-10-25",
      title: "Conclave",
      video: false,
      vote_average: 7.1,
      vote_count: 1136,
    },
    {
      adult: false,
      backdrop_path: "/7uGoDVlmB7JT2JrQ6fvNPoQeAo0.jpg",
      genre_ids: [16, 14, 12],
      id: 980477,
      original_language: "zh",
      original_title: "哪吒之魔童闹海",
      overview:
        "After the tribulation, although the souls of Ne Zha and Ao Bing were preserved, their physical bodies would soon be completely destroyed.Tai Yi Zhen Ren plans to use the Seven Colored Lotus to reshape their physical bodies. But in the process of reshaping their physical bodies, they encountered numerous difficulties. Where will the fate of Ne Zha and Ao Bing go?",
      popularity: 238.526,
      poster_path: "/293Mo4GWf7Tl0TfAr5NFghqeMy7.jpg",
      release_date: "2025-01-29",
      title: "Ne Zha 2",
      video: false,
      vote_average: 7.8,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: "/1LSMstNHwJnJD7tpnb8gZcgGNQR.jpg",
      genre_ids: [27, 53],
      id: 1164355,
      original_language: "id",
      original_title: "Lembayung",
      overview:
        "Arum and Pica, who wanted to complete their internship at Lembayung hospital, had to face mysterious terror from a woman satan who was suspected of hanged herself in the bathroom. The situation became even more tense after they asked others for help to the point where they threatened their own lives and those closest to them.",
      popularity: 233.778,
      poster_path: "/5x9LrW0yvtt6S3XovIQHgXfYvLL.jpg",
      release_date: "2024-09-19",
      title: "Lembayung",
      video: false,
      vote_average: 7.8,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/iXU87IdtNsYt7n6OigPJBDdbFf1.jpg",
      genre_ids: [10751, 16, 35, 28],
      id: 774370,
      original_language: "en",
      original_title: "Dog Man",
      overview:
        "When a faithful police dog and his human police officer owner are injured together on the job, a harebrained but life-saving surgery fuses the two of them together and Dog Man is born. Dog Man is sworn to protect and serve—and fetch, sit and roll over. As Dog Man embraces his new identity and strives to impress his Chief, he must stop the pretty evil plots of feline supervillain Petey the Cat.",
      popularity: 233.022,
      poster_path: "/89wNiexZdvLQ41OQWIsQy4O6jAQ.jpg",
      release_date: "2025-01-24",
      title: "Dog Man",
      video: false,
      vote_average: 7.3,
      vote_count: 31,
    },
  ],
};

module.exports = {
  upComingMovies,
};
